export const recipe = {
  vegetarian: true,
  vegan: false,
  glutenFree: false,
  dairyFree: true,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 11,
  gaps: "no",
  lowFodmap: false,
  aggregateLikes: 1,
  spoonacularScore: 44,
  healthScore: 8,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 78.53,
  extendedIngredients: [
    {
      id: 18064,
      aisle: "Bakery/Bread",
      image: "white-bread.jpg",
      consistency: "solid",
      name: "bread",
      nameClean: "bread",
      original: "2 slices of bread",
      originalString: "2 slices of bread",
      originalName: "bread",
      amount: 2,
      unit: "slices",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 2,
          unitShort: "slice",
          unitLong: "slices",
        },
        metric: {
          amount: 2,
          unitShort: "slice",
          unitLong: "slices",
        },
      },
    },
    {
      id: 1123,
      aisle: "Milk, Eggs, Other Dairy",
      image: "egg.png",
      consistency: "solid",
      name: "eggs",
      nameClean: "egg",
      original: "2 hard cooked eggs",
      originalString: "2 hard cooked eggs",
      originalName: "hard cooked eggs",
      amount: 2,
      unit: "",
      meta: ["hard", "cooked"],
      metaInformation: ["hard", "cooked"],
      measures: {
        us: {
          amount: 2,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 2,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 4025,
      aisle: "Condiments",
      image: "mayonnaise.png",
      consistency: "liquid",
      name: "mayo",
      nameClean: "mayonnaise",
      original: "1 tablespoon mayo",
      originalString: "1 tablespoon mayo",
      originalName: "mayo",
      amount: 1,
      unit: "tablespoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
    {
      id: 2046,
      aisle: "Condiments",
      image: "regular-mustard.jpg",
      consistency: "liquid",
      name: "mustard",
      nameClean: "mustard",
      original: "1 teaspoon mustard",
      originalString: "1 teaspoon mustard",
      originalName: "mustard",
      amount: 1,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
        metric: {
          amount: 1,
          unitShort: "tsp",
          unitLong: "teaspoon",
        },
      },
    },
    {
      id: 2047,
      aisle: "Spices and Seasonings",
      image: "salt.jpg",
      consistency: "solid",
      name: "salt",
      nameClean: "salt",
      original: "1/4 teaspoon salt",
      originalString: "1/4 teaspoon salt",
      originalName: "salt",
      amount: 0.25,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.25,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.25,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
    {
      id: 1002030,
      aisle: "Spices and Seasonings",
      image: "pepper.jpg",
      consistency: "solid",
      name: "pepper",
      nameClean: "black pepper",
      original: "1/8 teaspoon pepper",
      originalString: "1/8 teaspoon pepper",
      originalName: "pepper",
      amount: 0.125,
      unit: "teaspoon",
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.125,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
        metric: {
          amount: 0.125,
          unitShort: "tsps",
          unitLong: "teaspoons",
        },
      },
    },
  ],
  id: 645060,
  title: "Good-Egg Salad Sandwich",
  readyInMinutes: 45,
  servings: 1,
  sourceUrl: "https://www.foodista.com/recipe/R3ZSB6PY/good-egg-salad-sandwich",
  image: "https://spoonacular.com/recipeImages/645060-556x370.jpg",
  imageType: "jpg",
  summary:
    'Good-Egg Salad Sandwich could be just the <b>dairy free and lacto ovo vegetarian</b> recipe you\'ve been looking for. One serving contains <b>376 calories</b>, <b>17g of protein</b>, and <b>21g of fat</b>. This recipe serves 1 and costs 79 cents per serving. 1 person found this recipe to be delicious and satisfying. This recipe from Foodista requires bread, eggs, salt, and mustard. It works best as a main course, and is done in roughly <b>approximately 45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 42%</b>, which is pretty good. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/egg-salad-sandwich-567828">Egg Salad Sandwich</a>, <a href="https://spoonacular.com/recipes/egg-salad-sandwich-111297">Egg Salad Sandwich</a>, and <a href="https://spoonacular.com/recipes/the-best-egg-salad-sandwich-719308">The BEST Egg Salad Sandwich</a>.',
  cuisines: [],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: ["dairy free", "lacto ovo vegetarian"],
  occasions: [],
  winePairing: {
    pairedWines: [],
    pairingText: "",
    productMatches: [],
  },
  instructions:
    "Peel and mash eggs with a fork, combine with mayo, mustard, salt and pepper.\nSandwich mixture in bread slices.",
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Peel and mash eggs with a fork, combine with mayo, mustard, salt and pepper.",
          ingredients: [
            {
              id: 1102047,
              name: "salt and pepper",
              localizedName: "salt and pepper",
              image: "salt-and-pepper.jpg",
            },
            {
              id: 2046,
              name: "mustard",
              localizedName: "mustard",
              image: "regular-mustard.jpg",
            },
            {
              id: 1123,
              name: "egg",
              localizedName: "egg",
              image: "egg.png",
            },
            {
              id: 4025,
              name: "mayonnaise",
              localizedName: "mayonnaise",
              image: "mayonnaise.png",
            },
          ],
          equipment: [],
        },
        {
          number: 2,
          step: "Sandwich mixture in bread slices.",
          ingredients: [
            {
              id: 18064,
              name: "bread",
              localizedName: "bread",
              image: "white-bread.jpg",
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  originalId: null,
  spoonacularSourceUrl:
    "https://spoonacular.com/good-egg-salad-sandwich-645060",
};

export const search = {
  results: [
    {
      id: 632173,
      title: "Almond Rainbow Cake",
      image: "https://spoonacular.com/recipeImages/632173-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632176,
      title: "Almond Ricotta Cake",
      image: "https://spoonacular.com/recipeImages/632176-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632103,
      title: "Almond Butter Slices",
      image: "https://spoonacular.com/recipeImages/632103-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632100,
      title: "Almond Butter Cookies",
      image: "https://spoonacular.com/recipeImages/632100-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632105,
      title: "Almond Cacao Nut Balls",
      image: "https://spoonacular.com/recipeImages/632105-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632186,
      title: "Almond Snowball Cookies",
      image: "https://spoonacular.com/recipeImages/632186-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632179,
      title: "Almond Sandwich Cookies",
      image: "https://spoonacular.com/recipeImages/632179-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632137,
      title: "Almond Green Bean Salad",
      image: "https://spoonacular.com/recipeImages/632137-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632118,
      title: "Almond Cranberry Cookies",
      image: "https://spoonacular.com/recipeImages/632118-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 794538,
      title: "Almond Joy Protein Shake",
      image: "https://spoonacular.com/recipeImages/794538-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632203,
      title: "Almond-Grape Chicken Salad",
      image: "https://spoonacular.com/recipeImages/632203-312x231.jpg",
      imageType: "jpg",
    },
    {
      id: 632114,
      title: "Almond Chocolate Caramel Bars",
      image: "https://spoonacular.com/recipeImages/632114-312x231.jpg",
      imageType: "jpg",
    },
  ],
  offset: 12,
  number: 12,
  totalResults: 312,
};
